### ISSUE TITLE
Fix Jest Async Warning

### ISSUE THREAD

**Issue by zghera** [googleinterns/step53-2020#34]
### Issue summary

A Jest warning occurs when testing async functions. 

Other research suggests that jest mocked timers need to be used but experimentation showed that this causes other issues with exceeding jests timeouts (test never finished).

### Expected behavior

This warning should not appear (see below).

`ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at StreamProxy.Readable (../node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:179:22)
      at StreamProxy.Duplex (../node_modules/duplexify/node_modules/readable-stream/lib/_stream_duplex.js:67:12)
      at new Duplexify (../node_modules/duplexify/index.js:40:17)
      at new StreamProxy (../node_modules/@google-cloud/firestore/node_modules/google-gax/src/streamingCalls/streaming.ts:90:5)
      at StreamingApiCaller.init (../node_modules/@google-cloud/firestore/node_modules/google-gax/src/streamingCalls/streamingApiCaller.ts:46:12)`

{Fill in here}

### Steps to reproduce (including any preconditions)

run `npm test` in the root directory on the branch corresponding to #33.

![image](https://user-images.githubusercontent.com/39711376/86618792-80c36280-bf87-11ea-9846-776bea0f1725.png)

### Your environment

Include version numbers

- OS: {ChromeOS}
- Browser: {Chrome}

**Comment by zghera** [comment]
Likely not relevant anymore.
